## Build #1
FROM python:3.7-alpine as base

COPY ./requirements.txt /tmp
WORKDIR /install
RUN pip install --prefix=-/install -r /tmp/requirements.txt -v

## Build #2
FROM base
COPY --from=base /install /usr/local
WORKDIR /app
COPY . .
EXPOSE 5000
ENV FLASK_ENV=development
CMD flask run -h "0.0.0.0"
